#!/bin/bash

set -e

tmpfile=`mktemp /tmp/tempfile.XXXXXXXXX`
cp `rospack find bwi_guidance_solver`/perspectives/marvin.perspective $tmpfile
if [ "$1" == "ns" ]
then
  # A robot name has been specified. Simply replace the keyword marvin with supplied robot name.
  sed -i "s/marvin/$2/g" $tmpfile
else
  # No robot name specified, run everything in top level namespace.
  sed -i "s/\/marvin//g" $tmpfile
  sed -i "s/marvin\///g" $tmpfile
  sed -i "s/marvin//g" $tmpfile
fi
rosrun rqt_gui rqt_gui --perspective-file $tmpfile _font_size:=20
rm -f $tmpfile
